spring:
  application:
    name: "elfalyze"

app:
  name: ${spring.application.name}
  version:
    major: 0
    minor: 1
    patch: 0
  file-storage:
    # TODO Replace with non-local storage later
    type: local
    params:
      root-dir: ./file-storage/prod
